def change_vtt(insert_file_path):
	print ('./static'+insert_file_path)
	f = open('./static'+insert_file_path)
	text = f.read()
	f.close()
	print('is_vtt start???????')
	f = open('./static'+insert_file_path, 'w')
	f.write("WEBVTT\n\n")
	f.write(text)
	f.close()