"""empty message

Revision ID: 911e416ccb7a
Revises: 5451ed284890
Create Date: 2018-05-01 19:18:08.985116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '911e416ccb7a'
down_revision = '5451ed284890'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('anime_detail', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('anime_detail', 'created_at')
    # ### end Alembic commands ###
